---
title: "Santander svm starteR"
author: '@siero5335'
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(data.table)
library(tidyverse)
library(caret)
library(catboost)
library(pROC)
library(e1071)
```

## Including Plots

You can also embed plots, for example:

```{r}
tr <- fread("train.csv", header = T, showProgress = F)
te <- fread("test.csv", header = T, showProgress = F)
```


```{r}
tr$ID_code = NULL
te$ID_code = NULL

target = tr$target
summary(target)
table(target)

tr$target = NULL
```

```{r}
tr_tr <- trunc(tr)
te_tr <- trunc(te)


tr_digit0 <- tr %>% round() 
te_digit0 <- te %>% round()

tr_digit1 <- tr %>% round(1)
te_digit1 <- te %>% round(1)

tr_digit2 <- tr %>% round(2)
te_digit2 <- te %>% round(2)
```

```{r factor}
tr$f_var_68 <- as.factor(tr$var_68) %>%
  fct_lump(prop = 0.001)

te$f_var_68 <- as.factor(te$var_68) %>%
  fct_lump(prop = 0.001)
```

```{r FE}
fe_tr <- tr %>%
 group_by(f_var_68) %>%
 summarise_at(vars(starts_with("var")), c(mean, median, sd, skewness, kurtosis, sum, max, min))

fe_te <- te %>%
 group_by(f_var_68) %>%
 summarise_at(vars(starts_with("var")), c(mean, median, sd, skewness, kurtosis, sum,  max, min))
```

```{r join}
tr <- tr %>%
 left_join(fe_tr, by = "f_var_68")

te <- te %>%
 left_join(fe_te, by = "f_var_68")

rm(fe_tr, fe_te)
gc();gc()
```

```{r}
tr_aec <- fread("autoencoder/tr_aec.csv", header = T, showProgress = F)
te_aec <- fread("autoencoder/te_aec.csv", header = T, showProgress = F)

tr_umap <- fread("UMAP/tr_umap.csv", header = T, showProgress = F)
te_umap <- fread("UMAP/te_umap.csv", header = T, showProgress = F)

tr_knn <- fread("knnFE/knn_tr.csv", header = T, showProgress = F)
te_knn <- fread("knnFE/knn_te.csv", header = T, showProgress = F)

dn_aec <- fread("denoise auto encoder/Denoise_autoencode_seed71_400_200_512_500.csv",
                header = T, showProgress = F)


dn_aec$ID_code <- NULL
dn_aec$target <- NULL

tr_dn_aec <- dn_aec[1:200000, ]
te_dn_aec <- dn_aec[200001:400000, ]

#tr_OHE <- fread("OHE/ohe_tr_temp.csv", header = T, showProgress = F)
#te_OHE <- fread("OHE/ohe_te_temp.csv", header = T, showProgress = F)

train <- data.frame(tr, tr_digit0,  tr_tr, tr_aec, tr_umap, tr_dn_aec, tr_knn, tr_digit1, tr_digit2)
test <- data.frame(te, te_digit0, te_tr, te_aec, te_umap, te_dn_aec, te_knn, te_digit1, te_digit2)

train$f_var_68 <- NULL
test$f_var_68 <- NULL

rm(tr, tr_tr, tr_aec, tr_umap, tr_dn_aec, tr_knn, dn_aec, tr_digit0, tr_digit1, tr_digit2, 
   te, te_tr, te_aec, te_umap, te_dn_aec, te_knn, te_digit0, te_digit1, te_digit2)
gc();gc()
```

```{r}
dim(train) ; dim(test) ; setdiff(colnames(train) , colnames(test)) ; head(train) ; head(test)
```

```{r, warning=FALSE, error=FALSE}
set.seed(71)
target=ifelse(target==0,"No","Yes")
cctrl0 <- trainControl(method = "cv", number = 5, classProbs = TRUE,
                       summaryFunction = twoClassSummary)

nb_tune <- data.frame(usekernel =TRUE, fL = 0)

msa_caret <- train(
                      x = train,
                      y = target,
                      method = 'nb',
                      trControl = cctrl0,
                      tuneGrid = train_grid,
                      metric = "ROC",
                      preProc = c("center", "scale")
)
```

```{r}
msa_caret
```

```{r}
pred_test <- predict(msa_caret, newdata = test, type = "prob")
```

```{r}
sub <- fread("sample_submission.csv", header = T, showProgress = F)
sub$target = as.vector(pred_test$Yes)
head(sub)
fwrite(sub , "ridge8689.csv")
```  