---
title: "Santander LGB starteR"
author: '@siero5335'
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(data.table)
library(tidyverse)
library(caret)
library(lightgbm)
library(pROC)
library(e1071)
library(fBasics)
library(LauraeDS)
```

## Including Plots

You can also embed plots, for example:

```{r}
tr <- fread("train.csv", header = T, showProgress = F)
te <- fread("test.csv", header = T, showProgress = F)
```


```{r}
tr$ID_code = NULL
te$ID_code = NULL

target = tr$target
summary(target)
table(target)

tr$target = NULL
```

```{r load3}
tr_r <- fread("train.csv", header = T, showProgress = F)
te_r <- fread("test.csv", header = T, showProgress = F)

tr_r$ID_code = NULL
te_r$ID_code = NULL

tr_r$target = NULL
```

```{r row feature, error=FALSR, message=FALSE, warning=FALSE}
tr$sum <- rowSums(tr_r)
te$sum <- rowSums(te_r)

tr$rowmean <- rowMeans(tr_r)
te$rowmean <- rowMeans(te_r)

tr$rowSds <- rowSds(tr_r)
te$rowSds <- rowSds(te_r)

tr$rowVars <- rowVars(tr_r)
te$rowVars <- rowVars(te_r)

tr$rowSkewness <- rowSkewness(tr_r)
te$rowSkewness <- rowSkewness(te_r)

tr$rowKurtosis <- rowKurtosis(tr_r)
te$rowKurtosis <- rowKurtosis(te_r)

tr$rowMaxs <- rowMaxs(tr_r)
te$rowMaxs <- rowMaxs(te_r)

tr$rowMins <- rowMins(tr_r)
te$rowMins <- rowMins(te_r)

tr$rowQuantiles <- rowQuantiles(tr_r, prob = 0.05)
te$rowQuantiles <- rowQuantiles(te_r, prob = 0.05)

rm(tr2, te2, tr_r, te_r)
gc(); gc()
```

```{r}
tr_aec <- fread("autoencoder/tr_aec.csv", header = T, showProgress = F)
te_aec <- fread("autoencoder/te_aec.csv", header = T, showProgress = F)

tr_umap <- fread("UMAP/tr_umap.csv", header = T, showProgress = F)
te_umap <- fread("UMAP/te_umap.csv", header = T, showProgress = F)

#tr_knn <- fread("knnFE/knn_tr.csv", header = T, showProgress = F)
#te_knn <- fread("knnFE/knn_te.csv", header = T, showProgress = F)

#dn_aec <- fread("denoise auto encoder/Denoise_autoencode_seed71_400_200_512_500.csv", header = T, showProgress = F)


#dn_aec$ID_code <- NULL
#dn_aec$target <- NULL

#tr_dn_aec <- dn_aec[1:200000, ]
#te_dn_aec <- dn_aec[200001:400000, ]

#tr_OHE <- fread("OHE/ohe_tr_temp.csv", header = T, showProgress = F)
#te_OHE <- fread("OHE/ohe_te_temp.csv", header = T, showProgress = F)

train <- data.frame(tr, tr_aec, tr_umap)
test <- data.frame(te, te_aec, te_umap)

train$f_var_68 <- NULL
test$f_var_68 <- NULL

rm(tr, tr_aec, tr_umap, 
   te, te_aec, te_umap)
gc();gc()
```

```{r}
dim(train) ; dim(test) ; setdiff(colnames(train) , colnames(test)) ; head(train) ; head(test)
```

```{r}
nrounds = 5
set.seed(71)
folds = createFolds(factor(target), k = 5, list = FALSE)
```

```{r}
dev.result <-  rep(0, nrow(train)) 
pred_te <- rep(0, nrow(test))

tefinal = data.matrix(test)
rm(test)
gc();gc()
```


```{r}
for (this.round in 1:nrounds){      
      valid <- c(1:length(target)) [folds == this.round]
      dev <- c(1:length(target)) [folds != this.round]

      dtrain<- lgb.Dataset(data= as.matrix(train[dev,]), 
                           label= target[dev])
                           #weight = w[dev])
      dvalid <- lgb.Dataset(data= as.matrix(train[valid,]) , 
                            label= target[valid])
      valids <- list(val = dvalid)
      #### parameters are far from being optimal ####  
      p <- list(boosting_type = "gbdt", 
            objective = "binary",
            metric = "auc",
            learning_rate = 0.02, 
            max_depth = -1, 
            num_leaves = 2,
            bagging_fraction = 0.7,
            feature_fraction = 0.7,
            lambda_l1 = 5, 
            lambda_l2 = 5,
            min_child_weight = 19
               )
    
    model<- lgb.train(data = dtrain,
                params= p, 
                nrounds=100000,
                valids = list(val1=dtrain , val2 = dvalid),
                obj = "binary",
                eval_freq = 2000,
                early_stopping_rounds=500
      )
    
      pred = predict(model,as.matrix(train[valid,]))
      dev.result[valid] = pred  
      pred_test  = predict(model,tefinal)
  pred_te = pred_te +pred_test
}
```

```{r}
auc(target,dev.result)
pred_test = pred_te/nrounds
```

```{r}
sub <- fread("sample_submission.csv", header = T, showProgress = F)
sub$target = as.vector(pred_test)
head(sub)
fwrite(sub , "LGBM0.8989.csv")
```  

