---
title: "Santander LGB starteR"
author: '@siero5335'
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(data.table)
library(tidyverse)
library(caret)
library(lightgbm)
library(pROC)
library(e1071)
library(fBasics)
```

## Including Plots

You can also embed plots, for example:

```{r}
tr <- fread("train.csv", header = T, showProgress = F)
te <- fread("test.csv", header = T, showProgress = F)
```


```{r}
tr$ID_code = NULL
te$ID_code = NULL

target = tr$target
summary(target)
table(target)

tr$target = NULL
```

```{r}
tr_tr <- trunc(tr)
te_tr <- trunc(te)

tr_std <- scale(tr)
te_std <- scale(te)

tr_sin <- sin(tr)
te_sin <- sin(te)

tr_tan <- tan(tr)
te_tan <- tan(te)

tr_sinh <- sinh(tr)
te_sinh <- sinh(te)

tr_cumsum <- cumsum(tr)
te_cumsum <- cumsum(te)

tr_2q <- (tr)^2
te_2q <- (te)^2

tr_3q <- (tr)^3
te_3q <- (te)^3

tr_4q <- (tr)^4
te_4q <- (te)^4

tr_digit0 <- tr %>% round()
te_digit0 <- te %>% round()

tr_digit1 <- tr %>% round(1)
te_digit1 <- te %>% round(1)

tr_digit2 <- tr %>% round(2)
te_digit2 <- te %>% round(2)
```


```{r factor}
tr$f_var_68 <- as.factor(tr$var_68) %>%
  fct_lump(prop = 0.001)

te$f_var_68 <- as.factor(te$var_68) %>%
  fct_lump(prop = 0.001)
```

```{r FE}
fe_tr <- tr %>%
 group_by(f_var_68) %>%
 summarise_at(vars(starts_with("var")), c(mean, median, sd, skewness, kurtosis, sum, max, min))

fe_te <- te %>%
 group_by(f_var_68) %>%
 summarise_at(vars(starts_with("var")), c(mean, median, sd, skewness, kurtosis, sum, max, min))
```

```{r load2}
tr_r <- fread("train.csv", header = T, showProgress = F)
te_r <- fread("test.csv", header = T, showProgress = F)

tr_r$ID_code = NULL
te_r$ID_code = NULL

tr_r$target = NULL
```

```{r row feature, error=FALSR, message=FALSE, warning=FALSE}
tr$sum <- rowSums(tr_r[,-68])
te$sum <- rowSums(te_r[,-68])

tr$rowmean <- rowMeans(tr_r[,-68])
te$rowmean <- rowMeans(te_r[,-68])

tr$rowSds <- rowSds(tr_r[,-68])
te$rowSds <- rowSds(te_r[,-68])

tr$rowVars <- rowVars(tr_r[,-68])
te$rowVars <- rowVars(te_r[,-68])

tr$rowSkewness <- rowSkewness(tr_r[,-68])
te$rowSkewness <- rowSkewness(te_r[,-68])

tr$rowKurtosis <- rowKurtosis(tr_r[,-68])
te$rowKurtosis <- rowKurtosis(te_r[,-68])

tr$rowMaxs <- rowMaxs(tr_r[,-68])
te$rowMaxs <- rowMaxs(te_r[,-68])

tr$rowMins <- rowMins(tr_r[,-68])
te$rowMins <- rowMins(te_r[,-68])

tr$rowQuantiles <- rowQuantiles(tr_r[,-68], prob = 0.05)
te$rowQuantiles <- rowQuantiles(te_r[,-68], prob = 0.05)


tr$sum2 <- rowSums(tr_r)
te$sum2 <- rowSums(te_r)

tr$rowmean2 <- rowMeans(tr_r)
te$rowmean2 <- rowMeans(te_r)

tr$rowSds2 <- rowSds(tr_r)
te$rowSds2 <- rowSds(te_r)

tr$rowVars2 <- rowVars(tr_r)
te$rowVars2 <- rowVars(te_r)

tr$rowSkewness2 <- rowSkewness(tr_r)
te$rowSkewness2 <- rowSkewness(te_r)

tr$rowKurtosis2 <- rowKurtosis(tr_r)
te$rowKurtosis2 <- rowKurtosis(te_r)

tr$rowMaxs2 <- rowMaxs(tr_r)
te$rowMaxs2 <- rowMaxs(te_r)

tr$rowMins2 <- rowMins(tr_r)
te$rowMins2 <- rowMins(te)

tr$rowQuantiles2 <- rowQuantiles(tr_r, prob = 0.05)
te$rowQuantiles2 <- rowQuantiles(te_r, prob = 0.05)

rm(tr_r, te_r)
gc(); gc()
```


```{r join}
tr <- tr %>%
 left_join(fe_tr, by = "f_var_68")

te <- te %>%
 left_join(fe_te, by = "f_var_68")

rm(fe_tr, fe_te)
gc();gc()
```

```{r}
tr_aec <- fread("autoencoder/tr_aec.csv", header = T, showProgress = F)
te_aec <- fread("autoencoder/te_aec.csv", header = T, showProgress = F)

tr_umap <- fread("UMAP/tr_umap.csv", header = T, showProgress = F)
te_umap <- fread("UMAP/te_umap.csv", header = T, showProgress = F)

tr_knn <- fread("knnFE/knn_tr.csv", header = T, showProgress = F)
te_knn <- fread("knnFE/knn_te.csv", header = T, showProgress = F)

dn_aec <- fread("denoise auto encoder/Denoise_autoencode_seed71_400_200_512_500.csv",
                header = T, showProgress = F)


dn_aec$ID_code <- NULL
dn_aec$target <- NULL

tr_dn_aec <- dn_aec[1:200000, ]
te_dn_aec <- dn_aec[200001:400000, ]

#tr_OHE <- fread("OHE/ohe_tr_temp.csv", header = T, showProgress = F)
#te_OHE <- fread("OHE/ohe_te_temp.csv", header = T, showProgress = F)

train <- data.frame(tr, tr_tr, tr_aec, tr_umap, tr_dn_aec, tr_knn, tr_digit0, tr_digit1, tr_digit2, tr_2q, tr_3q, tr_4q, tr_std, tr_cumsum, tr_sin, tr_tan, tr_sinh)
test <- data.frame(te, te_tr, te_aec, te_umap, te_dn_aec, te_knn, te_digit0, te_digit1, te_digit2, te_2q, te_3q, te_4q, te_std, te_cumsum, te_sin, te_tan, te_sinh)

train$f_var_68 <- NULL
test$f_var_68 <- NULL

rm(tr, tr_tr, tr_aec, tr_umap, tr_dn_aec, tr_knn, tr_digit0, tr_digit1, tr_digit2, tr_2q, tr_3q, tr_4q, tr_std, tr_cumsum, tr_sin, tr_tan, tr_sinh, te, te_tr, te_aec, te_umap, te_dn_aec, te_knn, te_digit0, te_digit1, te_digit2, te_2q, te_3q, te_4q, te_std, te_cumsum, te_sin, te_tan, te_sinh, dn_aec)
gc();gc()
```

```{r}
dim(train) ; dim(test) ; setdiff(colnames(train) , colnames(test)) ; head(train) ; head(test)
```

```{r}
nrounds = 5
set.seed(2019)
folds = createFolds(factor(target), k = 5, list = FALSE)
```

```{r}
dev.result <-  rep(0, nrow(train)) 
pred_te <- rep(0, nrow(test))

tefinal = data.matrix(test)
rm(test)
gc();gc()
```

```{r}
for (this.round in 1:nrounds){      
      valid <- c(1:length(target)) [folds == this.round]
      dev <- c(1:length(target)) [folds != this.round]

      dtrain<- lgb.Dataset(data= as.matrix(train[dev,]), 
                           label= target[dev])
                           #weight = w[dev])
      dvalid <- lgb.Dataset(data= as.matrix(train[valid,]) , 
                            label= target[valid])
      valids <- list(val = dvalid)
      #### parameters are far from being optimal ####  
      p <- list(boosting_type = "gbdt", 
            objective = "binary",
            metric = "auc",  
            learning_rate = 0.02, 
            max_depth = -1, 
            num_leaves = 2,
            bagging_fraction = 0.7,
            feature_fraction = 0.7,
            lambda_l1 = 5, 
            lambda_l2 = 5,
            min_child_weight = 19
               )
    
    model<- lgb.train(data = dtrain,
                params= p, 
                nrounds=100000,
                valids = list(val1=dtrain , val2 = dvalid),
                metric="auc",
                obj = "binary",
                eval_freq = 2000,
                early_stopping_rounds=500
      )
    
      pred = predict(model,as.matrix(train[valid,]))
      dev.result[valid] = pred  
      pred_test  = predict(model,tefinal)
  pred_te = pred_te +pred_test
}
```

```{r}
auc(target,dev.result)
pred_test = pred_te/nrounds
```

```{r}
sub <- fread("sample_submission.csv", header = T, showProgress = F)
sub$target = as.vector(pred_test)
head(sub)
fwrite(sub , "LGBM0.897.csv")
```  

