---
title: "Santander LGB starteR"
author: '@siero5335'
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(data.table)
library(tidyverse)
library(caret)
library(lightgbm)
library(pROC)
library(e1071)
library(fBasics)
library(sm)
```

## Including Plots

You can also embed plots, for example:

```{r}
tr <- fread("train.csv", header = T, showProgress = F)
te <- fread("test.csv", header = T, showProgress = F)
```


```{r}
tr$ID_code = NULL
te$ID_code = NULL

target = tr$target
summary(target)
table(target)

tr$target = NULL

tr <- tr[, -c('var_90', 'var_161')]
te <- te[, -c('var_90', 'var_161')]
```

```{r load3}
tr_r <- fread("train.csv", header = T, showProgress = F)
te_r <- fread("test.csv", header = T, showProgress = F)

tr_r$ID_code = NULL
te_r$ID_code = NULL

tr_r$target = NULL

tr_r <- tr_r[, -c('var_90', 'var_161')]
te_r <- te_r[, -c('var_90', 'var_161')]
```

```{r row feature, error=FALSR, message=FALSE, warning=FALSE}
tr$sum <- rowSums(tr_r)
te$sum <- rowSums(te_r)

tr$rowSds <- rowSds(tr_r)
te$rowSds <- rowSds(te_r)

tr$rowSkewness <- rowSkewness(tr_r)
te$rowSkewness <- rowSkewness(te_r)

tr$rowKurtosis <- rowKurtosis(tr_r)
te$rowKurtosis <- rowKurtosis(te_r)

tr$rowMaxs <- rowMaxs(tr_r)
te$rowMaxs <- rowMaxs(te_r)

tr$rowMins <- rowMins(tr_r)
te$rowMins <- rowMins(te_r)

tr$rowQuantiles <- rowQuantiles(tr_r, prob = 0.05)
te$rowQuantiles <- rowQuantiles(te_r, prob = 0.05)
```

```{r factor}
forbin <- rbind(tr_r, te_r)
```

```{r factor}
forbin <- forbin %>%
  dplyr::mutate(
    var_68_bucket = cut(var_68, breaks = c(min(var_68), 5, 5.0005, 5.001, 5.0015, 5.002, 5.0025, 5.003, 5.0035, 5.004, 5.0045, 5.005,
                                     5.0055, 5.006, 5.0065, 5.007, 5.0075, 5.008, 5.0085, 5.009, 5.0095, 5.01, 
                                     5.0105, 5.011, 5.0115, 5.012, 5.0125, 5.013, 5.0135, 5.014, 5.0145, 5.015,
                                     5.0155, 5.016, 5.0165, 5.017, 5.0175, 5.018, 5.0185, 5.019, 5.0195, 5.02, 
                                     5.0205, 5.021, 5.0215, 5.022, 5.0225, 5.023, 5.0235, 5.024, 5.0245, 5.025,
                                     5.0255, 5.026, 5.0265, 5.027, 5.0275, 5.028, 5.0285, 5.029, 5.0295, 5.03, 
                                     5.0305, 5.031, 5.0315, 5.032, 5.0325, 5.033, 5.0335, 5.034, 5.0345, 5.035,
                                     5.0355, 5.036, 5.0365, 5.037, 5.0375, 5.038, 5.0385, 5.039, 5.0395, 5.04, max(var_68)))
  )
```

```{r factor}
tr_r$f_var_68 <- forbin$var_68_bucket[1:200000]
te_r$f_var_68 <- forbin$var_68_bucket[200001:400000]
```

```{r FE}
fe_tr <- tr_r %>%
 group_by(f_var_68) %>%
 summarise_at(vars(starts_with("var")), c(mean, sd, skewness, kurtosis))

fe_te <- te_r %>%
 group_by(f_var_68) %>%
 summarise_at(vars(starts_with("var")), c(mean, sd, skewness, kurtosis))
```

```{r join}
tr$f_var_68 <- forbin$var_68_bucket[1:200000]
te$f_var_68 <- forbin$var_68_bucket[200001:400000]

tr <- tr %>%
 left_join(fe_tr, by = "f_var_68")

te <- te %>%
 left_join(fe_te, by = "f_var_68")

rm(fe_tr, fe_te, tr_r, te_r, forbin)
gc();gc()
```

```{r}
tr_sin <- sin(tr[, c('var_12', 'var_53', 'var_6', 'var_166', 'var_148', 'var_133', 'var_169', 'var_9', 'var_95', 'var_91', 'var_93', 'var_131', 'var_71', 'var_68')])
te_sin <- sin(te[, c('var_12', 'var_53', 'var_6', 'var_166', 'var_148', 'var_133', 'var_169', 'var_9', 'var_95', 'var_91', 'var_93', 'var_131', 'var_71', 'var_68')])

tr_aec <- fread("denoising autoencoder 2/finaltrainset_dae2.csv", showProgress = F)
te_aec <- fread("denoising autoencoder 2/finaltrestset_dae2.csv", showProgress = F)

tr_umap <- fread("UMAP/tr_umap.csv", header = T, showProgress = F)
te_umap <- fread("UMAP/te_umap.csv", header = T, showProgress = F)

#tr_knn <- fread("knnFE/knn_tr.csv", header = T, showProgress = F)
#te_knn <- fread("knnFE/knn_te.csv", header = T, showProgress = F)

#dn_aec <- fread("denoise auto encoder/Denoise_autoencode_seed71_400_200_512_500.csv", header = T, showProgress = F)


#dn_aec$ID_code <- NULL
#dn_aec$target <- NULL

#tr_dn_aec <- dn_aec[1:200000, ]
#te_dn_aec <- dn_aec[200001:400000, ]

#tr_OHE <- fread("OHE/ohe_tr_temp.csv", header = T, showProgress = F)
#te_OHE <- fread("OHE/ohe_te_temp.csv", header = T, showProgress = F)

train <- data.frame(tr, tr_aec, tr_umap, tr_sin)
test <- data.frame(te, te_aec, te_umap, te_sin)

train$f_var_68 <- NULL
test$f_var_68 <- NULL

rm(tr, tr_aec, tr_umap, tr_sin, te_sin,
   te, te_aec, te_umap)
gc();gc()
```

```{r}
dim(train) ; dim(test) ; setdiff(colnames(train) , colnames(test)) ; head(train) ; head(test)
```

```{r}
nrounds = 5
set.seed(71)
folds = createFolds(factor(target), k = 5, list = FALSE)
```

```{r}
dev.result <-  rep(0, nrow(train)) 
pred_te <- rep(0, nrow(test))

tefinal = data.matrix(test)
rm(test)
gc();gc()
```


```{r}
for (this.round in 1:nrounds){      
      valid <- c(1:length(target)) [folds == this.round]
      dev <- c(1:length(target)) [folds != this.round]

      dtrain<- lgb.Dataset(data= as.matrix(train[dev,]), 
                           label= target[dev])
                           #weight = w[dev])
      dvalid <- lgb.Dataset(data= as.matrix(train[valid,]) , 
                            label= target[valid])
      valids <- list(val = dvalid)
      #### parameters are far from being optimal ####  
      p <- list(objective = "binary", 
               boost="gbdt",
               metric="auc",
               boost_from_average="false",
               num_threads=7,
               learning_rate = 0.008,
               num_leaves = 3,
               max_depth=-1,
               tree_learner = "serial",
               feature_fraction = 0.035,
               bagging_freq = 5,
               bagging_fraction = 0.33,
               min_data_in_leaf = 80,
               min_sum_hessian_in_leaf = 10.0,
               verbosity = 1)

    model<- lgb.train(data = dtrain,
                params= p, 
                nrounds=1000000,
                valids = list(val1=dtrain , val2 = dvalid),
                obj = "binary",
                eval_freq = 2000,
                early_stopping_rounds=3000
      )
    
      pred = predict(model,as.matrix(train[valid,]))
      dev.result[valid] = pred  
      pred_test  = predict(model,tefinal)
  pred_te = pred_te +pred_test
}
```

```{r}
auc(target,dev.result)
pred_test = pred_te/nrounds
```

```{r}
sub <- fread("sample_submission.csv", header = T, showProgress = F)
sub$target = as.vector(pred_test)
head(sub)
fwrite(sub , "LGBMtemp.csv")
```  

